apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoconn
  labels:
    app: mongoconn
  namespace: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoconn
  template:
    metadata:
      labels:
        app: mongoconn
    spec:
      containers:
        - name: mongoconn
          image: ranfangxu/mongoconn
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: mongoconn
  namespace: mongo
spec:
  ports:
    - name: web
      port: 8000
      targetPort: 8000

  selector:
    app: mongoconn
